const PrivacyInfo=(()=>{
 const tr=(...a)=>pickLangText(...a);
 const content=[
 ['Lokalt spel','Local game','Lokales Spiel'],
 ['Spelarnamn, inställningar, skinn, medaljer och lokal statistik sparas i denna webbläsare. Om du rensar webbplatsens sparade data kan de försvinna. Du kan spela utan att publicera tävlingsresultat.','Player names, settings, skins, medals and local statistics are stored in this browser. Clearing site data can remove them. You can play without publishing competition results.','Spielernamen, Einstellungen, Skins, Medaillen und lokale Statistiken werden in diesem Browser gespeichert. Das Löschen der Website-Daten kann sie entfernen. Du kannst ohne Veröffentlichung spielen.'],
 ['Veckans topplista','Weekly leaderboard','Wochenbestenliste'],
 ['När du väljer Publicera skickas tävlingsnamn, poäng, längsta orm och antal besvarade/rätt besvarade uppgifter till tjänsten på Loopia. Namn, poäng, längd, vecka och publiceringstid sparas. Uppgiftsantal används för rimlighetskontroll. Tävlingsnamn, poäng och längd visas offentligt. Välj ett smeknamn och undvik efternamn eller kontaktuppgifter.','When you choose Publish, your competition name, score, longest snake and answered/correct question counts are sent to the Loopia service. Name, score, length, week and publication time are stored. Question counts are used for plausibility checks. Competition name, score and length are public. Choose a nickname and avoid surnames or contact details.','Bei Veröffentlichen werden Wettbewerbsname, Punkte, längste Schlange und Anzahl beantworteter/richtiger Aufgaben an Loopia gesendet. Name, Punkte, Länge, Woche und Veröffentlichungszeit werden gespeichert. Aufgabenzahlen dienen Plausibilitätsprüfungen. Wettbewerbsname, Punkte und Länge sind öffentlich. Verwende einen Spitznamen ohne Nachnamen oder Kontaktdaten.'],
 ['Lagring och skydd','Storage and protection','Speicherung und Schutz'],
 ['Resultat sparas även efter veckans slut tills de tas bort av administratören. Varje omgång får en tillfällig kod för att förhindra dubbel publicering. Spambegränsningen använder en timvis föränderlig kod baserad på IP-adressen; den tas bort vid nästa skrivande anrop efter timmens slut. GitHub Pages levererar spelet och Loopia driver topplistan. Deras serverloggar kan innehålla IP-adresser.','Results remain after the week ends until removed by the administrator. Each round gets a temporary code to prevent duplicate publication. Spam protection uses an hourly changing code based on the IP address; it is removed on the next write request after the hour ends. GitHub Pages serves the game and Loopia hosts the leaderboard. Their server logs may contain IP addresses.','Ergebnisse bleiben nach Ende der Woche gespeichert, bis die Administration sie entfernt. Jede Runde erhält einen vorübergehenden Code gegen doppelte Veröffentlichung. Der Spamschutz verwendet einen stündlich wechselnden Code auf Basis der IP-Adresse; er wird beim nächsten Schreibzugriff nach Ablauf der Stunde gelöscht. GitHub Pages liefert das Spiel und Loopia betreibt die Bestenliste. Serverprotokolle können IP-Adressen enthalten.'],
 ['Kontakt och borttagning','Contact and removal','Kontakt und Löschung'],
 ['Ansvarig: Andreas Jonsson / 42 Improbable Owls. Kontakta support@42improbableowls.com för frågor, rättelse eller begäran om borttagning. Ange tävlingsnamn, vecka och resultat så att posten kan hittas. Du kan också lämna klagomål till Integritetsskyddsmyndigheten (IMY).','Responsible: Andreas Jonsson / 42 Improbable Owls. Contact support@42improbableowls.com with questions or correction/removal requests. Include competition name, week and result to help locate the entry. You may also complain to the Swedish Authority for Privacy Protection (IMY).','Verantwortlich: Andreas Jonsson / 42 Improbable Owls. Fragen und Berichtigungs-/Löschanfragen an support@42improbableowls.com. Gib Wettbewerbsname, Woche und Ergebnis an. Beschwerden sind auch bei der schwedischen Datenschutzbehörde IMY möglich.']
 ];
 function render(){
  $('aboutTabInfo').textContent=tr('Om spelet','About the game','Über das Spiel');$('aboutTabPrivacy').textContent=tr('Integritet','Privacy','Datenschutz');
  $('aboutTabs').setAttribute('aria-label',tr('Om och integritet','About and privacy','Über und Datenschutz'));
  const el=$('aboutPrivacy');el.replaceChildren();content.forEach((a,i)=>{const node=document.createElement(i%2?'p':'h3');node.textContent=tr(...a);el.append(node);});
  const link=document.createElement('a');link.href='mailto:support@42improbableowls.com';link.textContent='support@42improbableowls.com';el.append(link);
 }
 function select(view){render();const privacy=view==='privacy';$('aboutDetails').hidden=privacy;$('aboutPrivacy').hidden=!privacy;$('aboutTabInfo').setAttribute('aria-pressed',String(!privacy));$('aboutTabPrivacy').setAttribute('aria-pressed',String(privacy));}
 function open(){showAbout();select('privacy');}
 const details=$('aboutThanksText').parentElement;details.id='aboutDetails';const tabs=document.createElement('div');tabs.id='aboutTabs';tabs.setAttribute('role','group');tabs.innerHTML='<button class="export-btn" id="aboutTabInfo" aria-pressed="true"></button><button class="export-btn" id="aboutTabPrivacy" aria-pressed="false"></button>';details.before(tabs);const body=document.createElement('div');body.id='aboutPrivacy';body.hidden=true;details.after(body);$('aboutTabInfo').addEventListener('click',()=>select('about'));$('aboutTabPrivacy').addEventListener('click',()=>select('privacy'));select('about');
 return{select,open};
})();
