CREATE TABLE IF NOT EXISTS ss_challenges (
 id VARCHAR(8) PRIMARY KEY,
 iso_year SMALLINT UNSIGNED NOT NULL,
 iso_week TINYINT UNSIGNED NOT NULL,
 combination VARCHAR(80) NOT NULL,
 rules_json TEXT NOT NULL,
 starts_at BIGINT UNSIGNED NOT NULL,
 ends_at BIGINT UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS ss_runs (
 token_hash CHAR(64) PRIMARY KEY,
 challenge_id VARCHAR(8) NOT NULL,
 started_at BIGINT UNSIGNED NOT NULL,
 expires_at BIGINT UNSIGNED NOT NULL,
 used TINYINT UNSIGNED NOT NULL DEFAULT 0,
 INDEX (challenge_id), INDEX (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS ss_results (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 challenge_id VARCHAR(8) NOT NULL,
 name VARCHAR(12) NOT NULL,
 player_key CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
 score INT UNSIGNED NOT NULL,
 length SMALLINT UNSIGNED NOT NULL,
 created_at BIGINT UNSIGNED NOT NULL,
 UNIQUE KEY ss_player_week (challenge_id,player_key),
 INDEX (challenge_id, score), INDEX (challenge_id, length)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS ss_limits (
 bucket CHAR(64) PRIMARY KEY,
 hits INT UNSIGNED NOT NULL DEFAULT 0,
 expires_at BIGINT UNSIGNED NOT NULL,
 INDEX (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
